apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dharmatest-poi-map-app-dev
  annotations:
    argocd/app-name: dharmatest-poi-map-app-dev
    backstage.io/kubernetes-id: dharmatest-poi-map-app
    backstage.io/kubernetes-namespace: dharmatest
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-ms/dharmatest-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/dev-pipelines/ns/dharmatest/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/k8s/ns/dharmatest/deployments/dharmatest-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.igb2792k.eastus2.aroapp.io/#https://github.com/rhdh-ms/dharmatest-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://dharmatest-poi-map-app-dharmatest.apps.igb2792k.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/pdharmavaram"
  system: workshop-system-dharmatest
  consumesApis:
    - gateway-api-dharmatest
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-dharmatest
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/pdharmavaram"
